# Whether to enable icons
# Enabling icons require Nerd Fonts to be installed
enable_icons: false

# Specifying keys
# Multiple keys can be binded to a single action, where the format of each key is: `<modifier>+<key>`
# Where `modifier` is ctrl (control), shift (shift), esc (escape), etc
# And the key is the key - A, B, Z
#
# NOTE: Keys are case sensitive - A and a are treated as different keys

folders_keybindings:
    # Add a new folder
    # Default: ["A"]
    add: ["A"]

    # Edit a new folder
    # Default: ["E"]
    edit: ["E"]

    # Switches the focus to the next folder
    # Default: ["tab"]
    next: ["tab"]

    # Switches the focus to the previous folder
    # Default: ["shift+tab"]
    previous: ["shift+tab"]

    # Moves the focused token up
    # Default: ["ctrl+up"]
    move_up: ["ctrl+up"]

    # Moves the focused token down
    # Default: ["ctrl+down"]
    move_down: ["ctrl+down"]

    # Deletes the focused folder
    # Default: "D"
    delete: ["D"]

tokens_keybindings:
    # Add a new token
    # Default: ["a"]
    add: ["a"]

    # Edit a new token
    # Default: ["e"]
    edit: ["e"]

    # Switches the focus to the next token
    # Default: ["j"]
    next: ["j"]

    # Switches the focus to the previous folder
    # Default: ["k"]
    previous: ["k"]

    # Moves the focused token down
    # Default: ["K"]
    move_up: ["K"]

    # Moves the focused token up
    # Default: ["J"]
    move_down: ["J"]

    # Deletes the focused token
    # Default: ["d"]
    delete: ["d"]

    # Moves the focused token
    # Default: ["m"]
    move: ["m"]

    # Copies the code for the current token
    # Default: ["c"]
    copy: ["c"]

    # Add from screen
    # Default: ["s"]
    add_from_screen: ["s"]

    # Next token for HOTP based tokens
    # Default: ["n"]
    next_hotp: ["n"]

