# Keybindings

# Keybindings can be defined for a action in the following way:
#
# <action>: [<keys>]
#
# Examples:
#
# add: ["A"]
# move_down: ["ctrl", "down"]
#
# etc

folders:
    # Add a new folder
    # Default: ["A"]
    add: ["A"]

    # Edit a new folder
    # Default: ["E"]
    edit: ["E"]

    # Switches the focus to the next folder
    # Default: ["tab"]
    next: ["tab"]

    # Switches the focus to the previous folder
    # Default: ["shift+tab"]
    previous: ["shift+tab"]

    # Moves the focused token up
    # Default: ["ctrl+up"]
    move_up: ["ctrl+up"]

    # Moves the focused token down
    # Default: ["ctrl+down"]
    move_down: ["ctrl+down"]

    # Deletes the focused folder
    # Default: "D"
    delete: ["D"]

tokens:
    # Add a new token
    # Default: ["a"]
    add: ["a"]

    # Edit a new token
    # Default: ["e"]
    edit: ["e"]

    # Switches the focus to the next token
    # Default: ["j"]
    next: ["j"]

    # Switches the focus to the previous folder
    # Default: ["k"]
    previous: ["k"]

    # Moves the focused token down
    # Default: ["J"]
    move_up: ["J"]

    # Moves the focused token up
    # Default: ["K"]
    move_down: ["K"]

    # Deletes the focused token
    # Default: ["d"]
    delete: ["d"]

    # Moves the focused token
    # Default: ["m"]
    move: ["m"]

    # Copies the code for the current token
    # Default: ["c"]
    copy: ["c"]

    # Add from screen
    # Default: ["s"]
    add_from_screen: ["s"]

    # Next token for HOTP based tokens
    # Default: ["n"]
    next_hotp: ["n"]

